"""Build-time stamped constants. Generated by the build pipeline.

Source checkouts keep the SOURCE_BUILD sentinel — lifecycle enforcement is a
no-op so developers run the tool unrestricted. The build pipeline overwrites
this file with real values when packaging the binary.
"""

BUILD_DATE = "SOURCE_BUILD"
BUILD_ID = "source-build"
VERSION = "0.1.0"

# URL the binary fetches on startup. The JSON at this URL has one field:
#   {"last_day": ""}   — empty means run unrestricted
#   {"last_day": "2026-06-17"}  — die on next launch after that date
# The URL itself is the secret (secret gists are URL-protected).
REVOCATION_URL = ""
