"""Build-time stamped constants. Generated by the build pipeline.

Source checkouts keep the SOURCE_BUILD sentinel — lifecycle enforcement is a
no-op so developers run the tool unrestricted. The build pipeline overwrites
this file with real values when packaging the binary.
"""

BUILD_DATE = "SOURCE_BUILD"
BUILD_ID = "source-build"
VERSION = "0.1.0"

# Centralized revocation — filled in by the build script.
# Source builds use empty strings, which the lifecycle module treats as "skip".
REVOCATION_REPO = ""              # e.g. "krisk248/moonlight-revocations"
REVOCATION_FILE = "revoked.json"  # path inside that repo
REVOCATION_PAT = ""               # read-only fine-grained PAT
